### ISSUE TITLE
Set the buffer to AudioSource ?

### ISSUE THREAD

**Issue by ksk-S** [asus4/UnityNativeAudioPlugin#1]
I made it works in Windows.
I just wonder how to use it with AudioSource in Unity.

**Comment by asus4** [comment]
RtAudio runs on another thread from Unity. Copy native buffer from `OnNativeAudioIn` callback and set it in the main thread. (I'm not sure this old code still works though)

**Comment by ksk-S** [comment]
I made it. Thank you for your help. I just use audioclip.SetData() to set the buffer to AudioClip in Update() function. I will share it somewhere at some point.
